### ISSUE TITLE
Schedule F2F in Berlin?

### ISSUE THREAD

**Issue by caniszczyk** [cncf/wg-networking#1]
Is the Networking WG interested in an F2F in Berlin?

http://events.linuxfoundation.org/events/cloudnativecon-and-kubecon-europe/extend-the-experience/hackfestandsigs

cc: @cncf/cncf-networking-wg and @kenowens12

**Comment by leecalcote** [comment]
I'll join.

**Comment by jonboulle** [comment]
I'm interested.

**Comment by liljenstolpe** [comment]
I'm currently not planning on making it to berlin, but could join via a vc?

**Comment by liljenstolpe** [comment]
Do we have a date/location yet?

**Comment by caniszczyk** [comment]
@liljenstolpe I don't think so, but you can register for space here:
http://events.linuxfoundation.org/events/cloudnativecon-and-kubecon-europe/extend-the-experience/hackfestandsigs

cc: @cncf/cncf-networking-wg

**Comment by caniszczyk** [comment]
This is passed now.
