### ISSUE TITLE
Meeting details and invitations

### ISSUE THREAD

**Issue by feiskyer** [cncf/wg-networking#10]
It would be great if the meeting details (e.g. how to join the meeting and iCal links)  are included here.

cc @kenowens12

**Comment by feiskyer** [comment]
Sorry, didn't notice it is already included in README.

**Comment by leecalcote** [comment]
Good deal. I recently added those. Cheers.

**Comment by feiskyer** [comment]
@leecalcote Cool. Thanks. Could you also add a calendar so everyone can subscribe to the meeting changes automatically?

**Comment by leecalcote** [comment]
@feiskyer that's a great ask. We're getting closer. The readme has been updated with more meeting details.
