### ISSUE TITLE
Add meeting times / meeting minutes to README

### ISSUE THREAD

**Issue by caniszczyk** [cncf/wg-networking#4]
When the networking wg meets, we should make sure to document any meeting times and minutes to this repo / README (if that's the case, it's fine if all activities just happen over GitHub or a mailing list in an async fashion)

**Comment by leecalcote** [comment]
Additional notes posted into first [meeting minutes](https://docs.google.com/document/d/1rtbk27edum429Q5sEM5IP5FIu2i3qm7naXhZxFFJWs4/edit?usp=sharing).

**Comment by leecalcote** [comment]
Added proposed meeting times to README. I've a conflict with May 10th (OSCON will be in Austin on May 8th to 11th) and with the June 20th (Velocity in Santa Clara). Each of the Fridays of that week would work, if we're inclined to move the meeting time.

**Comment by caniszczyk** [comment]
This is fixed, thanks @leecalcote 

https://github.com/cncf/wg-networking/blob/master/README.md#meeting-minutes
